name: Industrial CI

on:
  push:
  workflow_dispatch:
jobs:
  call_reusable_workflow:
    uses: vortexntnu/vortex-ci/.github/workflows/reusable-industrial-ci.yml@main
    with:
        upstream_workspace: './dependencies.repos'
        skip_tests: true
